spring:
  application:
    name: client
server:
  port: 8090

#logging:
#  level:
#    root: info
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#
#management:
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0
