### client
GET http://localhost:8090/api/client/shake

### actuator
GET http://localhost:8090/actuator

### middleware
GET http://localhost:8091/api/middle/shake

### backend
GET http://localhost:8092/api/backend/shake