logging:
  level:
    root: info
  config: classpath:log4j2-spring.xml
  appender:
    kafka:
      bootstrap:
        servers: localhost:9092
      security:
        protocol: PLAINTEXT # PLAINTEXT, SASL_PLAINTEXT
      topic: errors
      username: username
      password: password
      group:
        id: 'logger-group'

management:
  tracing:
    enabled: true
  sampling:
    probability: 1.0
